const TOGGLE_LOADER = 'TOGGLE_LOADER';
const HIDE_LOADER = 'HIDE_LOADER';
const SET_MANAGER = "SET_MANAGER";
const SET_EMPLOYEE = "SET_EMPLOYEE";
const MANAGER_LOGOUT = "MANAGER_LOGOUT";
const EMPLOYEE_LOGOUT = "EMPLOYEE_LOGOUT";
const SET_USER = "SET_USER";
const USER_LOGOUT = "USER_LOGOUT";

export {
    TOGGLE_LOADER,
    HIDE_LOADER,
    SET_MANAGER,
    SET_EMPLOYEE,
    MANAGER_LOGOUT,
    EMPLOYEE_LOGOUT,
    SET_USER,
    USER_LOGOUT,
}