import { StyleSheet } from "react-native";
import { colors, fonts } from "../../constants";

export const styles = StyleSheet.create({
    header:{
        height: 56,
        backgroundColor: colors.b4FABEA,
        flexDirection: "row",
    },
    chevronleft: {
        color: "white",
        paddingLeft: 16.43,
        paddingVertical: 18,
        fontSize: fonts.H1,
        paddingRight: 99.57,
    },
    headerText: {
        paddingTop: 15,
        paddingRight: 90.03,
        paddingBottom: 17,
        lineHeight: 24,
        color: "white",
        fontFamily: fonts.PoppinsMedium,
        fontSize: fonts.H3,
        
    },
    logout: {
        paddingVertical: 18,
        paddingRight: 22.97,
        fontSize: fonts.H1,
        color: "white",
    },
    date: {
        fontFamily: fonts.PoppinsMedium,
        marginVertical: 20,
        marginLeft: 24,
        marginRight: 186,
        fontSize: fonts.H2,
        color: colors.b4F4F4F,
        lineHeight: 27,
    },
    summary: {
        height: 258,
        backgroundColor: "white",
        marginLeft: 23,
        marginRight: 23,
        marginBottom: 14,
        borderRadius: 10,
    },
    damacana: {
        flexDirection: "row",
    },
    damacanaText: {
        paddingLeft: 16,
        paddingVertical: 15,
        paddingRight: 143,
        lineHeight: 18.75,
        color: colors.b4F4F4F,
        fontSize: fonts.H3,
        fontFamily: fonts.PoppinsMedium,
    },
    damacanaAmount: {
        paddingTop: 12,
        paddingRight: 14,
        lineHeight: 24,
        fontSize: fonts.H3,
        fontFamily: fonts.PoppinsMedium,
        color: colors.b828282,
    },
    bardak: {
        flexDirection: "row",
    },
    bardakText: {
        paddingLeft: 16,
        fontFamily: fonts.PoppinsMedium,
        fontSize: fonts.H3,
        lineHeight: 18.75,
        color: colors.b4F4F4F,
    },
    bardakAmount: {
        lineHeight: 18.75,
        fontSize: fonts.H3,
        fontFamily: fonts.PoppinsMedium,
        color: colors.b828282,
        paddingRight: 14,
        paddingLeft: 68,
    },
    pet: {
        flexDirection: "row",
    },
    petText: {
        paddingTop: 15,
        lineHeight: 18.75,
        fontSize: fonts.H3,
        fontFamily: fonts.PoppinsMedium,
        paddingRight: 80,
        paddingLeft: 16,
        color: colors.b4F4F4F,
    },
    petAmount: {
        paddingTop: 11,
        lineHeight: 24,
        fontSize: fonts.H3,
        fontFamily: fonts.PoppinsMedium,
        marginRight: 14,
        color: colors.b828282,
    },
    seperator: {
        borderBottomWidth: 2,
        paddingTop: 15,
        borderBottomColor: colors.bF2F2F2,
    },
    toplamUrun: {
        flexDirection: "row",
    },
    urunText: {
        paddingTop: 15,
        lineHeight: 18.75,
        fontSize: fonts.H3,
        fontFamily: fonts.PoppinsMedium,
        paddingLeft: 16,
        paddingRight: 155,
        color: colors.b4F4F4F
    },
    urunAmount: {
        paddingTop: 12,
        lineHeight: 24,
        color: colors.b828282,
        fontSize: fonts.H3,
        fontFamily: fonts.PoppinsMedium,
    },
    toplamDepozito: {
        flexDirection: "row",
    },
    depozitoText: {
        paddingTop: 15,
        lineHeight: 18.75,
        fontFamily: fonts.PoppinsMedium,
        fontSize: fonts.H3,
        color: colors.b4F4F4F,
        paddingLeft: 16,
    },
    depozitoAmount: {
        paddingTop: 12,
        lineHeight: 24,
        color: colors.b6FCF97,
        paddingLeft: 69,
        fontSize: fonts.H3,
        fontFamily: fonts.PoppinsMedium
    },
    odenecekTutar: {
        flexDirection: "row",
    },
    odenecekText: {
        paddingVertical: 15,
        paddingLeft: 16,
        color: colors.b4F4F4F,
        fontFamily: fonts.PoppinsMedium,
        lineHeight: 24,
        fontSize: fonts.H3,
        paddingRight: 30,
        flex: 4,
    },
    odenecekAmount: {
        paddingVertical: 15,
        lineHeight: 24,
        flex: 1,
        paddingRight: 14,
        color: colors.b4FABEA,
        fontSize: fonts.H3,
    },
    kullanıcı: {
    flexDirection: "row",
    justifyContent: "space-between",
    },
    kullanıcıText: {
        marginTop: 19,
        marginLeft: 23,
        fontSize: fonts.H2,
        lineHeight: 27,
        fontFamily: fonts.PoppinsMedium,
        color: colors.b4F4F4F,
    },
    mobilebutton: {
        marginRight: 23,
        marginTop: 14,
        width: 75,
        height: 36,
        backgroundColor: colors.b4FABEA,
        borderRadius: 30,
    },
    telici: {
        flexDirection: "row"
    },
    icon: {
        padding: 8,
        fontSize: fonts.H1,
        color: "white",
    },
    aratext: {
        fontSize: fonts.H3,
        color: "white",
        paddingVertical: 6,
        fontFamily: fonts.PoppinsMedium,
    },
    musteriadi: {
        height: 56,
        backgroundColor: "white",
        marginHorizontal: 23,
        marginTop: 11,
        borderRadius: 10,
        paddingTop: 19,
        paddingLeft: 15,
    },
    musteriText: {
        fontFamily: fonts.RobotoRegular,
        lineHeight: 18.75,
        fontSize: fonts.H3,
        color: colors.b4F4F4F,
    },
    address: {
        flexDirection: "row",
        justifyContent: "space-between"
    },
    addressText: {
        fontFamily: fonts.PoppinsMedium,
        fontSize: fonts.H2,
        lineHeight: 27,
        color: colors.b4F4F4F,
        marginLeft: 23,
        marginTop: 20,
    },
    addressButton: {
        marginRight: 23,
        marginTop: 15,
        width: 106,
        height: 36,
        borderRadius: 30,
        backgroundColor: colors.bBB6BD9
    },
    adresici: {
        flexDirection: "row"
    },
    addressIcon: {
        padding: 8,
        fontSize: fonts.H1,
        color: "white",
    },
    konumText: {
        paddingVertical: 6,
        paddingLeft: 2,
        color: "white",
        fontFamily: fonts.PoppinsMedium,
        lineHeight: 24,
        fontSize: fonts.H3,
    },
    adresAlani: {
        height:131,
        borderRadius: 10,
        backgroundColor: "white",
        marginHorizontal: 23,
        marginTop: 11,
    },
    addressContent: {
        fontFamily: fonts.RobotoRegular,
        paddingLeft: 16,
        paddingTop: 15,
        paddingRight: 10,
        lineHeight: 18.75,
        fontSize: fonts.H3,
        color: colors.b4F4F4F
    },
    yoltarif: {
        fontFamily: fonts.PoppinsMedium,
        marginTop: 15,
        marginLeft: 16,
        marginBottom: 5,
        lineHeight: 18.75,
        fontSize: fonts.H3,
        color: colors.b4F4F4F,
    },
    tarifOzet: {
        paddingLeft: 15,
        fontFamily: fonts.RobotoRegular,
        fontSize: fonts.H3,
        lineHeight: 18.75,
        color: colors.b4F4F4F,
    },
    siparisAlan: {
        flexDirection: "row",
        justifyContent: "space-between"
    },
    siparis: {
        marginLeft: 23,
        marginTop: 26,
        lineHeight: 27,
        fontSize: fonts.H2,
        color: colors.b4F4F4F,
    },
    alertCircle: {
        marginTop: 21,
        marginRight: 23,
        width: 36,
        height: 36,
        backgroundColor: colors.bEB5757,
        borderRadius: 30,
    },
    alerticon: {
        padding: 8,
        fontSize: fonts.H1,
        color: "white",
    },
    not: {
        height: 56,
        marginHorizontal: 23,
        backgroundColor: "white",
        borderRadius: 10,
        marginTop: 11,
    },
    siparisText: {
        paddingLeft: 15,
        paddingTop: 19,
        color: colors.b4F4F4F,
        fontSize: fonts.H3,
        fontFamily: fonts.RobotoRegular,
        lineHeight: 18.75,
    },
    teslimat: {
        fontSize: fonts.H2,
        lineHeight: 27,
        marginLeft: 25,
        marginTop: 9,
        color: colors.b4F4F4F,
        fontFamily: fonts.PoppinsMedium,
    },
    teslimatTürü: {
        height: 56,
        marginHorizontal: 23,
        backgroundColor: "white",
        borderRadius: 7,
        marginTop: 15,
        marginBottom: 21,
    },
    teslimatTürüText: {
        paddingLeft: 15,
        paddingVertical: 19,
        fontFamily: fonts.RobotoRegular,
        fontSize: fonts.H3,
        lineHeight: 18.75,
        color: colors.b4F4F4F,
    },
    teslimEtButton: {
        height: 56,
        marginHorizontal: 23,
        backgroundColor: colors.b4FABEA,
        marginBottom: 20,
        borderRadius: 9,
    },
    teslimEtText: {
        paddingLeft: 124,
        marginVertical: 15,
        color: "white",
        fontSize: fonts.H2,
        fontFamily: fonts.PoppinsMedium,
        lineHeight: 27,
    }


})